# Generated by Django 2.2.5 on 2019-09-24 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('FactorId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True)),
                ('UserAddress', models.TextField()),
                ('ShipmentStatus', models.BooleanField()),
                ('ShipPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('OrderDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
