# Generated by Django 2.2.5 on 2019-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0003_auto_20190925_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='ShipmentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
