# Generated by Django 2.2.5 on 2019-09-24 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentStatus', models.BooleanField(default=False)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PaymentDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('FactorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factor.Factor')),
            ],
        ),
    ]
