# Generated by Django 2.2.5 on 2019-09-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190925_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='FactorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='factor.Factor'),
        ),
    ]
