# Generated by Django 2.2.5 on 2019-09-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=20)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('ProductQuantity', models.IntegerField()),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProductDescription', models.TextField()),
            ],
        ),
    ]
